### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by nexuslair** [Appdynamics/SQLMonitor#14]
Monitor initialization fails with below exception.
Please advise on the fix

```
[Agent-Monitor-Scheduler-1] 11 Aug 2022 18:28:51,220 ERROR SQLMonitor - Error while creating task for dbServer
java.lang.NullPointerException: null
	at com.appdynamics.extensions.sql.SQLMonitor.getConnectionProperties(SQLMonitor.java:113) ~[?:?]
	at com.appdynamics.extensions.sql.SQLMonitor.createTask(SQLMonitor.java:81) ~[?:?]
	at com.appdynamics.extensions.sql.SQLMonitor.doRun(SQLMonitor.java:49) [?:?]
	at com.appdynamics.extensions.AMonitorJob.run(AMonitorJob.java:50) [?:?]
	at com.appdynamics.extensions.ABaseMonitor.executeMonitor(ABaseMonitor.java:199) [?:?]
	at com.appdynamics.extensions.ABaseMonitor.execute(ABaseMonitor.java:187) [?:?]
	at com.singularity.ee.agent.systemagent.components.monitormanager.managed.MonitorTaskRunner.runTask(MonitorTaskRunner.java:149) [machineagent.jar:Machine Agent v21.12.6-3236 GA compatible with 4.4.1.0 Build Date 2022-01-15 06:37:49]
	at com.singularity.ee.agent.systemagent.components.monitormanager.managed.PeriodicTaskRunner.runTask(PeriodicTaskRunner.java:86) [machineagent.jar:Machine Agent v21.12.6-3236 GA compatible with 4.4.1.0 Build Date 2022-01-15 06:37:49]
	at com.singularity.ee.agent.systemagent.components.monitormanager.managed.PeriodicTaskRunner.run(PeriodicTaskRunner.java:47) [machineagent.jar:Machine Agent v21.12.6-3236 GA compatible with 4.4.1.0 Build Date 2022-01-15 06:37:49]
	at com.singularity.ee.util.javaspecific.scheduler.AgentScheduledExecutorServiceImpl$SafeRunnable.run(AgentScheduledExecutorServiceImpl.java:122) [agent-21.1.0-2340.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
	at com.singularity.ee.util.javaspecific.scheduler.ADFutureTask$Sync.innerRunAndReset(ADFutureTask.java:335) [agent-21.1.0-2340.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADFutureTask.runAndReset(ADFutureTask.java:152) [agent-21.1.0-2340.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.access$101(ADScheduledThreadPoolExecutor.java:119) [agent-21.1.0-2340.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.runPeriodic(ADScheduledThreadPoolExecutor.java:206) [agent-21.1.0-2340.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADScheduledThreadPoolExecutor$ADScheduledFutureTask.run(ADScheduledThreadPoolExecutor.java:236) [agent-21.1.0-2340.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADThreadPoolExecutor$Worker.runTask(ADThreadPoolExecutor.java:694) [agent-21.1.0-2340.jar:?]
	at com.singularity.ee.util.javaspecific.scheduler.ADThreadPoolExecutor$Worker.run(ADThreadPoolExecutor.java:726) [agent-21.1.0-2340.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

```

**Comment by satish-m** [comment]
Hi @nexuslair, this looks like configuration issue. Please create a zendesk ticket with all the details.
